* Description
  This repository includes code that allows a [[https://www.leapmotion.com/][Leapmotion]] to control a
  sound granulator.  A python script is used to get the data from the
  leap.  The sensor's data is then sent as OSC messages to
  SuperCollider where they are mapped to the parameters of a
  granulator.

* Dependencies
  - Linux or Mac OSX (not tested at all on Windows).
  - A [[http://store-us.leapmotion.com/products/leap-motion-controller][Leapmotion]].
  - The [[https://developer.leapmotion.com/v2][Leapmotion Desktop SDK]].
  - Python  > 2.7, < 3.0.
  - Python bindings for Leapmotion SDK.  (They should come with the SDK.)
  - [[http://github.com/radarsat1/liblo][liblo]] (OSC protocol library).
  - [[https://github.com/dsacre/pyliblo][pyliblo]] (liblo wrapper for python).
    - (Can be installed using pip, which is probably the easiest way.)
  - [[https://supercollider.github.io/][SuperCollider]] 3.7.
  - [[https://github.com/supercollider/sc3-plugins/releases][SC3-plugins]].
  - SuperCollider Quarks (extensions for SuperCollider).
    - dewdrop_lib
    - wslib
  - [[https://github.com/marierm/mmExtensions][mmExtensions]]
    - This is not a Quark yet, but it will become one shortly.

* Specifications
  At this point, the python script sends only a few selected
  parameters from the leapmotion.  It sends OSC messages to address
  224.0.0.1 on port 57120.  This is the /All Hosts/ [[https://en.wikipedia.org/wiki/Multicast_address][multicast address]],
  meaning that all machines on the same network segment should receive
  the messages.   (Some routers may not allow multicasting.)

  The address and port can easily be changed in the python script.


** /leapmotion/numhands
   The number of hands detected by the sensor.  This is sent only when
   the number changes.  This is good to start and stop processes.
** /leapmotion/hand/left
   Number of left hands.  Sent only when it changes.
** /leapmotion/hand/left/orientation
   3 floats: pitch, roll, yaw (in degrees).
** /leapmotion/hand/left/position
   3 floats: x, y, z.
** /leapmotion/hand/left/sphere/radius
   One float: the radius of a sphere fit to the curvature of this
   hand.  Small when fist is closed, large when hand is open. 
** /leapmotion/hand/right
   Number of right hands.  Sent only when it changes.
** /leapmotion/hand/right/orientation
   3 floats: pitch, roll, yaw (in degrees).
** /leapmotion/hand/right/position
   3 floats: x, y, z.
** /leapmotion/hand/right/sphere/radius
   One float: the radius of a sphere fit to the curvature of this
   hand.  Small when fist is closed, large when hand is open. 

 It may work with more than 2 hands, but I have not tested.
